version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g @vue/cli
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist