# This is a basic workflow to help you get started with Actions

name: DEPLOY

# Controls when the action will run. 
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    name: Build and deploy with SFTP

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up node js install and build
        uses: actions/setup-node@v2
        with:
          node-version: '8'
      - run: npm install
      - run: npm run build
        
      - name: Deploy files to server
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: 'dimipak.gr'
          username: ${{ secrets.USER_DIGITAL_OCEAN }}
          password: ${{ secrets.PASS_DIGITAL_OCEAN }}
          port: 22
          localDir: 'dist'
          remoteDir: '/var/www/dimipak'
